-- ================================================================================================
-- TITLE: auto-commands
-- ABOUT:
--    Automatically run code on defined events (e.g. save, yank)
--    Autocmds are automatically loaded on the VeryLazy event
--    Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- ================================================================================================
